blank_issues_enabled: true
contact_links:
  - name: "⚠️ PRs not accepted until July 2026"
    url: https://github.com/OpenCoven/coven/blob/main/CONTRIBUTING.md
    about: "We are only accepting Issues and Bug Reports right now. Please read CONTRIBUTING.md before opening a PR."
